name: Publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule: 
   - cron: '0 12 * * 0'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        version:
        - 2022
        - 2019
    runs-on: windows-${{ matrix.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        run: cmd /c "docker build --build-arg VERSION=ltsc${{ matrix.version }} -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.IMG_NAME }}:ltsc${{ matrix.version }} $('-t ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.IMG_NAME }}'*(${{ matrix.version }} -eq '2022')) ."
      - name: Push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.IMG_NAME }} --all-tags
