name: Docker Image CI

on:
  schedule: 
   - cron: '0 12 * */1 0'
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        WIN_VER:
        - ltsc2022
        - ltsc2025
#        - ltsc2019
        - 20H2
        - 2004
        - 1809
    runs-on: windows-2025
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        shell: cmd
        run: >
          docker build
          --build-arg VERSION=${{ matrix.WIN_VER }}
          --tag=${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.IMG_NAME }}:${{ matrix.WIN_VER }}
          --tag=ghcr.io/${{ github.repository_owner }}/${{ vars.IMG_NAME }}:${{ matrix.WIN_VER }}
          --isolation=hyperv
          .

      - name: Tag latest Windows version
        if: strategy.job-index == 0
        shell: cmd
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.IMG_NAME }}:${{ matrix.WIN_VER }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.IMG_NAME }}
          docker tag ghcr.io/${{ github.repository_owner }}/${{ vars.IMG_NAME }}:${{ matrix.WIN_VER }} ghcr.io/${{ github.repository_owner }}/${{ vars.IMG_NAME }}

      - name: Tag same images (20H2 -> 2009)
        if: ${{ matrix.WIN_VER == '20H2' }}
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.IMG_NAME }}:${{ matrix.WIN_VER }} docker tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.IMG_NAME }}:2009
          docker tag ghcr.io/${{ github.repository_owner }}/${{ vars.IMG_NAME }}:${{ matrix.WIN_VER }} ghcr.io/${{ github.repository_owner }}/${{ vars.IMG_NAME }}:2009

      - name: Push
        shell: cmd
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.IMG_NAME }} --all-tags
          docker push ghcr.io/${{ github.repository_owner }}/${{ vars.IMG_NAME }} --all-tags

  trigger-next-workflow:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Trigger next workflow (docker-msys2-mingw-w64-toolchain)
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: docker-image.yml
          repo: amitie10g/docker-msys2-mingw-w64-toolchain
          token: ${{ secrets.DOCKER_MSYS2_MINGW_W64_TOOLCHAIN_TOKEN }}
